apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  containers:
    - name: wordpress
      image: wordpress:4.8-apache
  initContainers:
    - name: mysql
      image: mysql:5.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypass